# Base configs
baseurl: "https://www.gustav.tech/Cheria/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics:

# UI configs
title: "Cheria Portfolio"
subtitle: "My work"
author:
header:
 title: "Portfolio"
 subtitle: "by Cheria"
footer:
 name: "Wanna get in contact?"
 bio: "Feel free to reach out to me"
web_design: 
social_urls:
  facebook:
  twitter: 
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: 
  linkedin: 
  github:
