# Base configs
baseurl: "https://www.gustav.tech/Cheria/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics:

# UI configs
title: "Cheria Portfolio"
subtitle: "My work"
author:
header:
 title: "Chéria's Portfolio"
 subtitle:
footer:
 name: "About me"
 bio: "Born: 1983"
      "From: Republic of Congo"               
web_design: 
social_urls:
  facebook:
  twitter: 
  instagram: "https://www.instagram.com/cheria_essieke/"
  dribbble: 
  linkedin: 
  github:
